Добавляет базовую стилизацию страниц
htmlacademy-adaptive/1953411-cat-energy-25 pull request #4
Opened 2022-04-09 14:45 UTC by TimelierComb

2022-04-09 18:05 UTC, oksanych requested changes

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +  font-family: "Arial", sans-serif;
Шрифт лучше вынести в переменную и обрати внимание та этот критерий - https://up.htmlacademy.ru/adaptive/25/criteries#b10

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +.additional-product-card {
Для каждого блока нужно создавать отдельный scss файл, но много блоков тоже не хорошо, поэтому подумай нужен ли тебе блок или лучше реализовать элементом блока.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +.additional-information-list {
Тут такая же ситуация как и выше, комментарий к 14-й строке в этом файле.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +  font-family: "Arial", sans-serif;
Так нужно сделать во всем проекте.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +  color: #444444;
Все цвета лучше вынести в переменные и уже эти переменные использовать в проекте.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/additional-products.scss
> +.special-offer {
В блоке additional-products.scss находиться блок .special-offer, для каждого блока нужно создавать отдельный файл.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/body.scss
> +@font-face {
Стили для шрифтов вынеси в отдельный файл, назови его fonts.scss

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/body.scss
> +.body {
Эти стили можно написать для тега боди, создать новый файл global.scss и вынести их туда.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/button.scss
> +
Удали пустую строку.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/contacts.scss
> +.address {
Файл называеться contacts.scss a класс блока .address, файл и класс блока должны иметь одинаковое название

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/example.scss
> +.achievement-list__number {
Два блока в одном файле, нужно вынести в отдельный файл

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/example.scss
> +.index-toggler__description {
Тут тоже нужно вынести в отдельный файл или переписать класс.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/info.scss
> +.steps-list {
Два блока в одном файле, нужно вынести в отдельный файл

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/main-footer.scss
> +.social__list {
В этом файле три блока, нужно переписать.

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/main-header.scss
> +.site-list {
Два блока в одном файле, нужно вынести в отдельный файл

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/products.scss
> +.information-list__name {
Два блока в одном файле, нужно вынести в отдельный файл

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/program.scss
> +.card-program {
Два блока в одном файле, нужно вынести в отдельный файл

2022-04-09 18:05 UTC, oksanych commented on source/sass/blocks/visually-hidden.scss
> +.visually-hidden {
Этот класс можно вынести в файл global.scss тогда не нужно будет для него создавать отдельный файл.

2022-04-09 18:05 UTC, oksanych commented on source/catalog.html
>            <p class="address__description">ул. Большая Конюшенная, д. 19/8<br>Санкт-Петербург</p>
Почитай про этот тег - https://www.w3schools.com/tags/tag_address.asp
Лучше использовать его в этом случае

2022-04-10 08:48 UTC, TimelierComb commented on source/sass/blocks/additional-products.scss
> +.additional-product-card {
Тут я подумал, что лучше оставить блок. В отдельный файл вынес.

2022-04-10 08:49 UTC, TimelierComb commented on source/sass/blocks/additional-products.scss
> +.additional-information-list {
Здесь переделал в элемент блока. По-моему, нормально получилось.

2022-04-10 08:51 UTC, TimelierComb commented on source/sass/blocks/additional-products.scss
> +.special-offer {
Я этот блок сделал элементом блока additional-products. Если будет необходимо, то снова в отдельный блок переделаю, но сейчас не вижу такой надобности

2022-04-10 09:08 UTC, TimelierComb commented on source/sass/blocks/products.scss
> +.information-list__name {
Здесь переделал в элемент блока product-card.

2022-04-10 09:09 UTC, TimelierComb commented on source/sass/blocks/main-header.scss
> +.site-list {
Вынес в отдельный файл.

2022-04-10 09:11 UTC, TimelierComb commented on source/sass/blocks/program.scss
> +.card-program {
Вынес в отдельный файл

2022-04-10 09:14 UTC, TimelierComb commented on source/catalog.html
>            <p class="address__description">ул. Большая Конюшенная, д. 19/8<br>Санкт-Петербург</p>
поменял тэг на address на всех страницах.

2022-04-10 10:08 UTC, TimelierComb commented on source/sass/blocks/additional-products.scss
> +  font-family: "Arial", sans-serif;
Вынес в переменные и к шрифту Oswald добавил вторым Arial.

2022-04-10 10:09 UTC, TimelierComb commented on source/sass/blocks/additional-products.scss
> +  color: #444444;
Внес цвета в переменные и поменял их в стилях.

2022-04-10 10:10 UTC, TimelierComb commented on source/sass/blocks/visually-hidden.scss
> +.visually-hidden {
Перенес в global и добавил туда же переменные для цветов и шрифтов.

2022-04-10 18:30 UTC, TimelierComb commented on source/sass/blocks/main-footer.scss
> +.social__list {
Тут я разделил на три файла.

2022-04-10 18:32 UTC, TimelierComb commented on source/sass/blocks/contacts.scss
> +.address {
Поменял название на address.scss

2022-04-10 18:33 UTC, TimelierComb commented on source/sass/blocks/example.scss
> +.achievement-list__number {
Сделал новый файл achivement-list.scss.

2022-04-10 18:37 UTC, TimelierComb commented on source/sass/blocks/example.scss
> +.index-toggler__description {
Вынес в отдельный файл. При стилизации уже окончательно пойму можно ли его делать элементом или оставить как отдельный блок.

2022-04-10 18:38 UTC, TimelierComb commented on source/sass/blocks/info.scss
> +.steps-list {
Вынес в отдельный файл.

2022-04-10 18:39 UTC, TimelierComb commented on source/sass/blocks/body.scss
> +@font-face {
Вынес в отдельный файл fonts.scss

2022-04-10 18:40 UTC, TimelierComb commented on source/sass/blocks/body.scss
> +.body {
перенес в global.scss и переделал класс в тег. сам файл body.scss удалил.

2022-04-10 18:45 UTC, TimelierComb commented on source/sass/blocks/button.scss
> +
Удалил

2022-04-10 18:56 UTC, merged