Module4 task1
htmlacademy-adaptive/1953411-cat-energy-25 pull request #5
Opened 2022-04-18 17:41 UTC by TimelierComb

2022-04-18 18:43 UTC, oksanych requested changes

2022-04-18 18:43 UTC, oksanych commented on source/sass/blocks/presentation.scss
> +    color: $black;
Тут не нужно задавать цвет, он уже переопредлён на таблете.

2022-04-18 18:43 UTC, oksanych commented on source/sass/blocks/main-header.scss
> +    display: none;
Это можно удалить, так как на задаешь на таблете display: none.

2022-04-18 18:43 UTC, oksanych commented on source/sass/blocks/main-header.scss
> +    background-color: transparent;
Зачем тут задавать background-color: transparent; - выше не вижу чтобы задавался цвет для background, значит нечего и делать прозрачным.

2022-04-18 18:43 UTC, oksanych commented on source/sass/blocks/program.scss
> +  box-sizing: border-box;
Напиши глобально, а тут удали, но возможно нужно будет после этого поправить други блоки

```
* {
  box-sizing: border-box;
}
```

2022-04-20 07:48 UTC, TimelierComb commented on source/sass/blocks/presentation.scss
> +    color: $black;
Удалил.

2022-04-20 07:49 UTC, TimelierComb commented on source/sass/blocks/main-header.scss
> +    display: none;
Удалил.

2022-04-20 07:49 UTC, TimelierComb commented on source/sass/blocks/main-header.scss
> +    background-color: transparent;
Удалил.

2022-04-20 07:51 UTC, TimelierComb commented on source/sass/blocks/program.scss
> +  box-sizing: border-box;
Перенес в global.scss, во всех остальных файлах удалил.

2022-04-20 19:31 UTC, merged