Module5 task2
htmlacademy-adaptive/1953411-cat-energy-25 pull request #8
Opened 2022-05-08 19:08 UTC by TimelierComb

2022-05-09 17:07 UTC, oksanych requested changes

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/main-form.scss
> +    margin: 24px auto  38px;
Лишний пробел после auto.

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/main-form.scss
> +      margin: 65px auto  76px;
Лишний пробел после auto.

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/product-card.scss
> +  @media (min-width: $tablet-width) {
В строке 75 и 85 min-width: $tablet-width, и для чего в строке 86 делать line-height: 21px ?

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/questionary.scss
> +  @media (min-width: $tablet-width) {
В строке 51 и 57 min-width: $tablet-width

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/site-list.scss
> +    &--current::before {
Эти стили можно перенести в min-width: $desktop-width в сроке 83.

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/product-card.scss
> +  @media (min-width: $tablet-width) {
Строка 19 и 31 min-width: $tablet-width

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/products.scss
> +    background-color: #ebebeb;
Вынести цвет в переменную.

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/product-card.scss
> +    background-color: #d3d3d3;
Вынести цвет в переменную

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/product-card.scss
> +    background-color: #ebebeb;
Вынести цвет в переменную

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/presentation.scss
> +      linear-gradient(to right, $white 50%, #62a53b 50%);
Вынести цвет в переменную

2022-05-09 17:07 UTC, oksanych commented on source/sass/blocks/button.scss
> +    background-color: #ebebeb;
Вынести цвет в переменную.

2022-05-10 11:56 UTC, TimelierComb commented on source/sass/blocks/main-form.scss
> +    margin: 24px auto  38px;
Убрал.

2022-05-10 11:59 UTC, TimelierComb commented on source/sass/blocks/product-card.scss
> +  @media (min-width: $tablet-width) {
Исправил. Тут медиа должен был быть для $desktop-width

2022-05-10 12:00 UTC, TimelierComb commented on source/sass/blocks/questionary.scss
> +  @media (min-width: $tablet-width) {
Исправил. Тут медиа должен был быть для $desktop-width.

2022-05-10 12:08 UTC, TimelierComb commented on source/sass/blocks/site-list.scss
> +    &--current::before {
Тут не получится, так псевдоэлемент относится к .site-list__item, а на 83 строке стили для site-list__link.

2022-05-10 19:15 UTC, merged